steps:
# Build the container image
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}', '.']
  id: Building the container image
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:${SHORT_SHA}']
  id: Pushing the image to registry
# Deploy container image to gke
- name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - 'set'
  - 'image'
  - 'deployment'
  - 'cicd'  # It's the workload/deployment name
  - 'gke-image-sha256-1=gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA' # gke-image-sha256
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cicd-cluster'
